SELECT CITY, LENGTH(CITY) FROM STATION WHERE LAT_N>0 and LAT_N>0 ORDER BY LENGTH(CITY), CITY LIMIT 1;
SELECT CITY, LENGTH(CITY) FROM STATION WHERE LAT_N>0 and LAT_N>0 ORDER BY LENGTH(CITY) DESC, CITY LIMIT 1;
